version: '3'

services:
  tortoisebot-ros2-real:
    image: tortoisebot_ros2_real
    network_mode: host
    privileged: true

    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
      - /dev/video0:/dev/video0:rw
      - /dev/gpiomem:/dev/gpiomem
    environment:

      - ROS_DOMAIN_ID=07

    build:
      context: ./real
      dockerfile: ./Dockerfile
