version: '3'

services:
  tortoisebot-ros2-real:
    image: tortoisebot_ros2_real
    network_mode: host
    ipc: host
    pid: host
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
      - /dev/video0:/dev/video0:rw
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - ROS_IPV6=on
    build:
      context: ./real
      dockerfile: ./Dockerfile
